### ISSUE TITLE
fix handling of dates for fetching target data

### ISSUE THREAD

**Issue by elray1** [hubverse-org/hub-dash-site-builder#7]
The logic for getting dates to use for target data file names is incorrect; we should just use the reference date that's provided as a function argument.  The current logic seems to fail at certain times of day, and doesn't reliably return the correct data when it succeeds.  See the changes in PR #5 for suggested logic.

**Comment by zkamvar** [comment]
The problem is that the forecasts are partitioned by the forecasts for a given `referenceDate` (e.g. [`wk-inc-flu-hosp_01_2023-10-28.json`](https://github.com/hubverse-org/hub-dashboard-template/blob/ptc/data/forecasts/wk-inc-flu-hosp_01_2023-10-28.json) and [`wk-inc-flu-hosp_01_2023-11-04.json`](https://github.com/hubverse-org/hub-dashboard-template/blob/ptc/data/forecasts/wk-inc-flu-hosp_01_2023-11-04.json)), but the targets have a single date (e.g. `wk-inc-flu-hosp_01_2024-11-23.json` that is determined by [the `reference_date_from_today()` function in hub-dashboard-predtimechart](https://github.com/hubverse-org/hub-dashboard-predtimechart/blob/3e1696a00cf1e90a016538363db10d5bf0bbf692/src/hub_predtimechart/app/generate_target_json_files_FluSight.py#L60-L70).

So, the visualization would only for the current `referenceDate`, but the data would fail to load for all other reference dates.

That being said, I will test your fix and see if it works.

**Comment by zkamvar** [comment]
That being said, since we overwrite the target data every time we regenerate it and the date does not vary, I would _much_ prefer if we remove the date from the file on the data generation end.

**Comment by elray1** [comment]
> That being said, since we overwrite the target data every time we regenerate it and the date does not vary, I would much prefer if we remove the date from the file on the data generation end.

This indicates a problem with our procedures: rather than overwriting the target data, we should be adding new files with the new reference dates.  The goal of this is to be able to show in the visualization the latest available target data (for direct comparison with the forecasts) as well as the target data that was available as of the currently-selected reference date (to see what models were seeing).  Here's a screenshot from the viz of flu predictions from last season showing an example for Texas where the data were revised downwards after forecasts were generated: 
![image](https://github.com/user-attachments/assets/2556691e-f2f5-4930-b206-7c55724fb986)

We want to be able to show this kind of situation.  The way this works in predtimechart is that it fetches the target data with two reference dates: the latest available and the one that you're currently viewing in the viz.  For that to work, we need to:

1. Keep all past versions of target data
2. Respect the requested `referenceDate` in the fetch data call.

**Comment by zkamvar** [comment]
> This indicates a problem with our procedures: rather than overwriting the target data, we should be adding new files with the new reference dates. The goal of this is to be able to show in the visualization the latest available target data (for direct comparison with the forecasts) as well as the target data that was available as of the currently-selected reference date (to see what models were seeing). 

Ahhhh gotcha. In my defense, I could not find any clear documentation about what the expected inputs and outputs were in a broader context. 


In light of this, I believe that #5 is then correct and then I will need to update https://github.com/hubverse-org/hub-dashboard-control-room/blob/main/scripts/pushit.sh to not clean everything

**Comment by elray1** [comment]
> In my defense, I could not find any clear documentation about what the expected inputs and outputs were in a broader context.

I totally understand :)

The plan sounds good!
